config/routes.rb
Rails.application.routes.draw do
  resources :records, except: [:new, :edit] do
    collection do
      get 'new_a', to: 'records#new_a'
      get 'new_mx', to: 'records#new_mx'

      resources :record_as, except: :index, path: 'a'
      resources :record_mxes, except: :index, path: 'mx'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
module Record
  def self.table_name_prefix
    'record_'
  end
end

app/models/record/a.rb
module Record
  class A < Base
    validates_uniqueness_of :name
    
  end
end

app/models/record/base.rb
module Record
  class Base < ApplicationRecord
    self.abstract_class = true
    validates_presence_of :name, :value, :ttl_seconds
    validates_numericality_of :ttl_seconds, greater_than_or_equal_to: 0

    scope :active, ->{ where(active: true) }

    def self.type_s
      name.demodulize
    end

    def type_s
      self.class.type_s
    end
  end
end

app/models/record/mx.rb
module Record
  class MX < Base
    validates_numericality_of :priority, greater_than_or_equal_to: 0

  end
end

app/models/replica.rb
class Replica < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/record_as_controller.rb
class RecordAsController < ApplicationController
  before_action :set_current_record, except: [:new, :create]

  def new
    @record = Record::A.new
  end

  def create
    @record = Record::A.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to records_path, notice: 'Record created' }
        format.json { render :show, status: :created }
      else
        format.html { render "new_#{@record.type_s}" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to records_path, notice: 'Record updated' }
        format.json { render :show, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_path, notice: 'Record deleted' }
      format.json { head :no_content }
    end
  end

  def set_current_record
    id = params[:id] || params[:record_id]
    @record = Record::A.find(id)
  end

  def record_params
    params.require(:record_a).permit(:name, :value, :ttl_seconds, :active)
  end
end

app/controllers/record_mxes_controller.rb
class RecordMxesController < ApplicationController
  before_action :set_current_record, except: [:new, :create]

  def new
    @record = Record::MX.new
  end

  def create
    @record = Record::MX.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to records_path, notice: 'Record created' }
        format.json { render :show, status: :created }
      else
        format.html { render "new_#{@record.type_s}" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to records_path, notice: 'Record updated' }
        format.json { render :show, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_path, notice: 'Record deleted' }
      format.json { head :no_content }
    end
  end

  def set_current_record
    id = params[:id] || params[:record_id]
    @record = Record::MX.find(id)
  end

  def record_params
    params.require(:record_mx).permit(:name, :value, :ttl_seconds, :active, :priority)
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_records

  def index
  end

  private

  def set_records
    @records = Record::A.all + Record::MX.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def pretty_bool(bool)
    bool ? '✔' : '✘'
  end

  def error_block(model, field)
    messages = model.errors.full_messages_for(field)

    p_tags = messages.map do |msg|
      content_tag :p, class: 'help-block' do
        msg.capitalize
      end
    end

    p_tags.join.html_safe
  end
end

app/helpers/record_as_helper.rb
module RecordAsHelper
end

app/helpers/record_mxes_helper.rb
module RecordMxesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CruDns</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/record/as/_a.html.haml
= cache record do
  %tr
    %td
      = record.type_s
    %td
      = record.name
    %td= record.value
    %td
      = record.ttl_seconds
    %td= pretty_bool(record.active?)
    %td -
    %td
      = link_to edit_record_a_path(record) do
        = fa_icon 'pencil'

      &nbsp;

      = link_to record_path(record),
                method: :delete,
                data: { confirm: 'Are you sure?' },
                class: 'text-danger' do
        = fa_icon 'trash-o'

app/views/record/mxes/_mx.html.haml
= cache record do
  %tr
    %td
      = record.type_s
    %td
      = record.name
    %td= record.value
    %td
      = record.ttl_seconds
    %td= pretty_bool(record.active?)
    %td= record.priority
    %td
      = link_to edit_record_mx_path(record) do
        = fa_icon 'pencil'

      &nbsp;

      = link_to record_path(record),
                method: :delete,
                data: { confirm: 'Are you sure?' },
                class: 'text-danger' do
        = fa_icon 'trash-o'

app/views/record_as/_form.html.haml
= form_for @record do |f|

  %div.form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  %div.form-group
    = f.label :value
    = f.text_field :value, class: 'form-control'

  %div.form-group
    = f.label :ttl_seconds
    = f.number_field :ttl_seconds, min: 0, step: 60, class: 'form-control'

  %div.checkbox
    = f.label :active do
      = f.check_box :active
      Active

  = f.submit 'Save', class: 'btn btn-default'

app/views/record_as/edit.html.haml
= cache @record do
  .container.main-container
    .row
      %main.col-md-9
        %header
          %h1 RecordAs#edit
        %section
          = render 'form', record: @record
      %aside.col-md-3

app/views/record_as/new.html.haml
= cache @record do
  .container.main-container
    .row
      %main.col-md-9
        %header
          %h1 RecordAs#new
        %section
          = render 'form', record: @record
      %aside.col-md-3

app/views/record_mxes/_form.html.haml
= form_for @record do |f|

  %div.form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  %div.form-group
    = f.label :value
    = f.text_field :value, class: 'form-control'

  %div.form-group
    = f.label :ttl_seconds
    = f.number_field :ttl_seconds, min: 0, step: 60, class: 'form-control'

  %div.form-group
    = f.label :priority
    = f.number_field :priority, min: 0, step: 1, class: 'form-control'

  %div.checkbox
    = f.label :active do
      = f.check_box :active
      Active

  = f.submit 'Save', class: 'btn btn-default'

app/views/record_mxes/edit.html.haml
= cache @record do
  .container.main-container
    .row
      %main.col-md-9
        %header
          %h1 RecordMxes#edit
        %section
          = render 'form', record: @record
      %aside.col-md-3

app/views/record_mxes/new.html.haml
= cache @record do
  .container.main-container
    .row
      %main.col-md-9
        %header
          %h1 RecordMxes#new
        %section
          = render 'form', record: @record
      %aside.col-md-3

app/views/records/_new_buttons.html.haml
= link_to 'New A record', new_record_a_path, class: %w(btn btn-default)
= link_to 'New MX record', new_record_mx_path, class: %w(btn btn-default)

app/views/records/index.html.haml
= cache @records do
  .container.main-container
    .row
      %main.col-md-9
        %header
          %h1 Records#index
        %section
          %table.table
            %thead
              %tr
                %th{colspan: 2} Record
                %th Value
                %th TTL (seconds)
                %th Active
                %th Priority
                %th
            %tbody
              - @records.each do |record|
                = render record, record: record

        %section
          = render 'new_buttons'

      %aside.col-md-3